# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2026, Loan Bernat

[project]
name = "magma_bench"
version = "0.1.0"
description = "Benchmark code to execute and evaluate your model on the MAGMA-BENCHMARK"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["magma_core>=0.1.0","magma_scenarios>=0.1.0"]

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
